Repository tardis-sn/carsus, pull requests merged in 2022-01, with the labels that each got.

#251 add CMFGEN photoionization cross-sections
  carsus/__init__.py
  carsus/conftest.py
  carsus/data/cmfgen_config.yml
  carsus/io/chianti_/chianti_.py
  carsus/io/cmfgen/__init__.py
  carsus/io/cmfgen/base.py
  carsus/io/cmfgen/util.py
  carsus/io/kurucz/gfall.py
  carsus/io/nist/ionization.py
  carsus/io/nist/weightscomp.py
  carsus/io/output/base.py
  carsus/io/tests/test_base.py
  carsus/io/tests/test_cmfgen.py
  carsus/io/tests/test_ionization.py
  carsus/io/tests/test_legacy_consistency.ipynb
  carsus/io/tests/test_nist_weightscomp.py
  carsus/io/tests/test_output_base.ipynb
  carsus/io/zeta.py
  carsus_env3.yml
  docs/io/cmfgen.ipynb
  docs/quickstart.ipynb
Labels: feature

#264 Add pandoc to fix doc build
  carsus_env3.yml
Labels: documentation

#265 Fix doc build badge
  README.rst
Labels: priority-low
