Repository tardis-sn/carsus, pull requests merged in 2025-05, with the labels that each got.

#451 Remove pytest arraydiff
  carsus/io/tests/test_chianti.py
  carsus/io/tests/test_cmfgen.py
Labels: testing :vertical_traffic_light:

#414 Export raw Chianti collision and A_ul data instead of pre-processing
  .github/workflows/docs-build.yml
  .github/workflows/tests.yml
  carsus/__init__.py
  carsus/io/chianti_/chianti_.py
  carsus/io/nist/ionization.py
  carsus/io/output/base.py
  carsus/io/output/collisions.py
  carsus/io/output/levels_lines.py
Labels: :fire:

#455 CMFGEN reader exports A_ul for lines
  carsus/io/cmfgen/base.py
Labels: cmfgen, build-docs, git-lfs-pull
